#!/usr/bin/env python3
"""Build _data/contributors.yml — who actually maintains the API specifications and their tooling.

Public contribution counts from the GitHub API, nothing else. No employers, no affiliations, no
inferred anything: a GitHub login and a number of commits to a named repository, both of which
anyone can re-check. Bots are dropped.

The point of the list is the funding argument. The specifications this industry runs on are
maintained by a countable number of named people, and almost none of them are paid to do it by
the organizations that depend on it most.

Usage:
    python3 scripts/fetch_contributors.py

Auth: GITHUB_TOKEN or GH_TOKEN in the environment, else `gh auth token`.
"""

import json
import os
import subprocess
import sys
import urllib.error
import urllib.request
from datetime import datetime, timezone

# (repo, kind, label) — the specifications this ecosystem depends on, and the tooling that runs them.
REPOS = [
    ("OAI/OpenAPI-Specification", "specification", "OpenAPI"),
    ("OAI/Arazzo-Specification", "specification", "Arazzo"),
    ("OAI/Overlay-Specification", "specification", "Overlays"),
    ("asyncapi/spec", "specification", "AsyncAPI"),
    ("json-schema-org/json-schema-spec", "specification", "JSON Schema"),
    ("stoplightio/spectral", "tooling", "Spectral"),
    ("daveshanley/vacuum", "tooling", "vacuum"),
    ("Redocly/redocly-cli", "tooling", "Redocly CLI"),
    ("speclynx/apidom", "tooling", "SpecLynx ApiDOM"),
    ("zalando/zally", "tooling", "Zally"),
]

TOP_N = 12


def token():
    for var in ("GITHUB_TOKEN", "GH_TOKEN"):
        if os.environ.get(var):
            return os.environ[var]
    try:
        return subprocess.check_output(["gh", "auth", "token"], text=True).strip()
    except Exception:
        sys.exit("No GitHub token: set GITHUB_TOKEN or authenticate with `gh auth login`.")


def api(tok, path):
    req = urllib.request.Request(
        f"https://api.github.com{path}",
        headers={
            "Authorization": f"bearer {tok}",
            "Accept": "application/vnd.github+json",
            "User-Agent": "spotlight-contributors",
        },
    )
    try:
        with urllib.request.urlopen(req) as resp:
            return json.load(resp)
    except urllib.error.HTTPError as exc:
        print(f"  ! {path}: HTTP {exc.code}", file=sys.stderr)
        return None


def yaml_escape(value):
    return '"' + str(value).replace("\\", "\\\\").replace('"', '\\"') + '"'


def main():
    tok = token()
    out = []
    for slug, kind, label in REPOS:
        people = api(tok, f"/repos/{slug}/contributors?per_page=100")
        if not people:
            continue
        people = [p for p in people if p.get("type") != "Bot" and not p["login"].endswith("[bot]")]
        people.sort(key=lambda p: -p.get("contributions", 0))
        out.append(
            {
                "repo": slug,
                "label": label,
                "kind": kind,
                "url": f"https://github.com/{slug}",
                "contributor_count": len(people),
                "top": [
                    {"login": p["login"], "url": p["html_url"], "contributions": p["contributions"]}
                    for p in people[:TOP_N]
                ],
            }
        )
        print(f"  {slug}: {len(people)} contributors")

    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    path = os.path.join(root, "_data", "contributors.yml")
    with open(path, "w") as fh:
        fh.write("# Generated by scripts/fetch_contributors.py — do not edit by hand.\n")
        fh.write("# Public GitHub contribution counts only. No employers, no affiliations, no\n")
        fh.write("# inferred anything. Re-run the script to refresh.\n")
        fh.write(f"# Generated: {datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')}\n")
        fh.write(f"# Note: the GitHub contributors endpoint counts commits, and caps at 100 entries\n")
        fh.write("# per repository — treat contributor_count as 'at least this many'.\n\n")
        for repo in out:
            fh.write(f"- repo: {yaml_escape(repo['repo'])}\n")
            fh.write(f"  label: {yaml_escape(repo['label'])}\n")
            fh.write(f"  kind: {repo['kind']}\n")
            fh.write(f"  url: {repo['url']}\n")
            fh.write(f"  contributor_count: {repo['contributor_count']}\n")
            fh.write("  top:\n")
            for person in repo["top"]:
                fh.write(
                    f"    - {{ login: {yaml_escape(person['login'])}, "
                    f"url: {person['url']}, contributions: {person['contributions']} }}\n"
                )
            fh.write("\n")
    print(f"{path}: {len(out)} repositories")


if __name__ == "__main__":
    main()
